name: sync-apt-repository
on:
  push:
    branches:
      - master

jobs:
    generate-dist-and-archive-repo:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Install Apt repo management tools
              run: |
                sudo apt update
                sudo apt install -y dpkg-dev apt-utils
            
            - name: Generate dist folder with apt package metadata
              run: |
                cd forsakenidol
                ../populate-dist.sh
            
            - name: Confirm that the directory structure is correct
              run: |
                cd ..
                tree

            - name: Tar the deb repo structure
              run: |
                mv ./index.html ./forsakenidol/
                tree forsakenidol
                tar -czf deb.tar.gz ./forsakenidol
            
            - name: Upload deb archive
              uses: actions/upload-artifact@v6
              with:
                name: deb.tar.gz
                path: deb.tar.gz

    sync-repo-upstream:
      needs: generate-dist-and-archive-repo
      runs-on: ubuntu-latest
      environment: production
      steps:
        # We don't have to checkout the repo for this stage; just download the archive structure
        - name: Download deb archive
          uses: actions/download-artifact@v7
          with:
            name: deb.tar.gz
        
        - name: Unpack deb archive
          run: |
            mkdir ./forsakenidol
            tar -xzf deb.tar.gz -C ./forsakenidol/
            mv forsakenidol/index.html .
        
        - name: Verify resulting repo directory structure
          run: |
            pwd
            tree
        
        # Next steps: Authenticate to Azure, check for and install azcopy (if required), sync directory structure
