name: sync-apt-repository
on:
    workflow_run:
      workflows: [ "sync-terraform-config" ]
      types:
        - completed
jobs:
    generate-dist-and-update-azure-package-repo:
        runs-on: ubuntu-22.04
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Install Apt repo management tools
              run: |
                sudo apt update
                sudo apt install -y dpkg-dev apt-utils
            
            - name: Generate dist folder with apt package metadata
              run: |
                cd forsakenidol
                ../populate-dist.sh
            
            - name: Confirm that the directory structure is correct
              run: |
                cd ..
                tree
