name: sync-apt-repository
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    generate-dist-folder:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Apt repo management tools
              run: |
                sudo apt update
                sudo apt install -y dpkg-dev apt-utils
            
            - name: Generate dist folder with apt package metadata
              run: |
                cd forsakenidol
                ../populate-dist.sh
            
            - name: Confirm that the directory structure is correct
              run: |
                cd ..
                tree