name: terraform
on:
    push:
        branches:
            - master
jobs:
    check-terraform-config:
        runs-on: ubuntu-22.04
        defaults:
            run:
                working-directory: terraform
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Authenticate to HCP Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.14.3"
                cli_config_credentials_hostname: "app.terraform.io"
                cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

            - name: Show Terraform CLI config
              run: |
                ls -R ~
                echo "Trying ~/.terraform.d/credentials.tfrc.json"
                cat ~/.terraform.d/credentials.tfrc.json || echo "no credentials.tfrc.json"
                echo "Trying ~/.terraformrc"
                cat ~/.terraformrc || echo "no .terraformrc"
                
            - name: Initialize terraform
              run: |
                pwd
                terraform init -input=false

            - name: Validate configuration
              run: |
                pwd
                terraform validate

            - name: Plan infrastructure
              run: |
                pwd
                terraform plan
