name: sync-terraform-config
on:
  push:
    branches:
      - master

permissions:
  id-token: write   # Required to allow workflow to request JWT from GitHub's OIDC provider
  contents: read
  issues: write     # Required for manual approval step

jobs:
    check-then-apply-terraform-config:
        runs-on: ubuntu-22.04
        defaults:
            run:
                working-directory: terraform
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Authenticate to HCP Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.14.3"
                cli_config_credentials_hostname: "app.terraform.io"
                cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

            - name: Initialize terraform
              run: terraform init -input=false

            - name: Validate configuration
              run: terraform validate

            - name: Authenticate to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Verify that Azure Authentication worked
              run: az account show

            - name: Plan infrastructure
              run: terraform plan -out=tf.plan

            - name: (Approval Gate) Deploy to production
              uses: trstringer/manual-approval@v1.12.0
              timeout-minutes: 7
              with:
                secret: ${{ github.token }}
                approvers: forsakenidol
                minimum-approvals: 1
            
            - name: Apply previous plan
              run: terraform apply tf.plan
